[env]
TERM = "xterm-256color"

[font]
size = 14.0
normal.family = "UbuntuMono Nerd Font"

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
padding.x = 10
padding.y = 10
decorations = "none"
opacity = 0.2
blur = true
