[tools]
"cargo:stau" = "latest"
"github:itaysk/kubectl-neat" = "latest"
"github:ramonvermeulen/whosthere" = "latest"
"github:sinclairtarget/git-who" = "latest"
"github:vmware/govmomi" = "latest"
"npm:@cyclonedx/cdxgen" = "latest"
"npm:@googleworkspace/cli" = "latest"
"npm:agent-browser" = "latest"
"npm:ctx7" = "latest"
"npm:skills" = "latest"
"pipx:black" = "latest"
"pipx:yubikey-manager" = "latest"
age = "latest"
bat = "latest"
biome = "latest"
btop = "latest"
bun = "latest"
consul = "latest"
cyclonedx = "latest"
dagger = "latest"
delta = "latest"
eza = "latest"
fnox = "latest"
gcloud = "latest"
glab = "latest"
helm = "latest"
jj = "latest"
k6 = "latest"
k9s = "latest"
kind = "latest"
krew = "latest"
kubectl = "latest"
kustomize = "latest"
lazygit = "latest"
neovim = "latest"
node = "24"
opentofu = "latest"
pi = "latest"
prettier = "latest"
python = "latest"
redis = "latest"
shellcheck = "latest"
talosctl = "latest"
terraform = "latest"
terragrunt = "latest"
usage = "latest"
uv = "latest"
vault = "latest"
yamlfmt = "latest"
yazi = "latest"
zoxide = "latest"
