stau install btop --force
stau install fzf --force
stau install gh --force
stau install git --force
stau install jj --force
stau install k9s --force
stau install lazy --force
stau install oktofetch --force
stau install tmux --force
stau install yazi --force
stau install zsh --force
