# This applies for new installs. Old installs will keep the old behaviour unless configured otherwise.
enter_accept = true

## Set commands that will be completely ignored from stats
ignored_commands = [
  "^ls",
  "^gfa",
  "^gst",
  "^gl",
  "^tmus",
]

[sync]
# Enable sync v2 by default
# This ensures that sync v2 is enabled for new installs only
# In a later release it will become the default across the board
records = true
